apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: workload
          image: varshapetclinicacr973.azurecr.io/spring-petclinic:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres

            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://demo-db:5432/petclinic

            - name: SPRING_DATASOURCE_USERNAME
              value: petclinic

            - name: SPRING_DATASOURCE_PASSWORD
              value: petclinic

            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
